# See : https://github.com/moove-it/sidekiq-scheduler
# See : http://www.crontab-generator.org/

# Receipts are generated at Tierion at each 10 minute
# interval (0, 10, 20, 30, 40, 50). Since Tierion could in
# practice take a few minutes to process after each 10 min interval
# run this five minutes after their intervals. This is really a
# sweeper cleanup-process to make sure we get everything. The real-time
# processing should occur when Tierion sends their callback when the 10
# minute blocks are processed and ready for pickup.
BlockchainGetReceiptsWorker:
  cron: "05,15,25,35,45,55 * * * *"
  description: "Check for new blockchain receipts and store them locally."

# Check if any receipts that were queued have since been confirmed
# as having the Merkle root stored in a confirmed BTC transaction.
BlockchainGetReceiptConfirmationsWorker:
  cron: "*/5 * * * *"
  description: "Check for new blockchain receipt confirmations and store them locally."
